server:
  port: 8080
spring:
  jackson:
    deserialization:
      ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT : true
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
news:
  host: http://newsservice.demo-app.svc.cluster.local
  path: /news
weather:
  host: http://weather-app-svc.demo-app.svc.cluster.local
  path: /get-weather?id=
ads:
    host: http://ad-app-svc.demo-app.svc.cluster.local
    path: /
pa:
  host: http://prod-avail.demo-app.svc.cluster.local
  path: /product-availability