apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-avail
  namespace: demo-app
spec:
  selector:
    matchLabels:
      app: prod-avail
  template:
    metadata:
      labels:
        app: prod-avail
    spec:
      containers:
        - name: prod-avail
          env:
            - name: KEY
              value: org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://ecom-data.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=oAWGjDDWndiaM99k15rZwCOIDI8Wqf0RvIlK7Zed4cI=";
          image: tibinlukose/product-availability:v.1.3
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: prod-avail
  namespace: demo-app
spec:
  type: ClusterIP
  selector:
    app: prod-avail
  ports:
    - port: 80
      targetPort: 8080
      name: prod-avail-port
