server:
  port: 8080
spring:
  kafka:
    bootstrap-servers: ecom-data.servicebus.windows.net:9093
    client-id: product-availbility-1
    properties:
      sasl.jaas.config: ${JAAS}
      sasl.mechanism: PLAIN
      security.protocol: SASL_SSL
    consumer:
      group-id: product-availbility
      properties:
        spring.json:
          use.type.headers: false
          value.default.type: in.zycon.demo.pa.products.Product
topic:
  name: ecom-sku-stock