apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: myfiles
build:
  artifacts:
  - image: python-weather-app
deploy:
  kubectl:
    manifests:
    - k8s-deployment.yaml
    - k8s-service.yaml
