apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: weather-app-svc
  name: weather-app-svc
spec:
  ports:
  - name: "weather-port"
    port: 80
    protocol: TCP
    targetPort: 5000
    nodePort: 31243
  selector:
    app: weather-app
  type: NodePort
status:
  loadBalancer: {}