apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsservice
  namespace: demo-app
spec:
  selector:
    matchLabels:
      app: newsservice
  template:
    metadata:
      labels:
        app: newsservice
    spec:
      containers:
        - name: newsservice
          image: tibinlukose/news-app
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: newsservice
  namespace: demo-app
spec:
  type: ClusterIP
  selector:
    app: newsservice
  ports:
    - port: 80
      targetPort: 8080
      name: news-port
