apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: strapi-pvc
  namespace: demo-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi
  namespace: demo-app
spec:
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      containers:
        - name: strapi
          image: strapi/strapi
          ports:
            - containerPort: 1337
          volumeMounts:
            - mountPath: "/srv/app"
              name: strapi
      volumes:
        - name: strapi
          persistentVolumeClaim:
            claimName: strapi-pvc
        - name: strapi-conf
          configMap:
              name: strapi-server

---
apiVersion: v1
kind: Service
metadata:
  name: strapi
  namespace: demo-app
spec:
  selector:
    app: strapi
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 1337