apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayservice
  namespace: demo-app
spec:
  selector:
    matchLabels:
      app: gatewayservice
  template:
    metadata:
      labels:
        app: gatewayservice
    spec:
      containers:
        - name: gatewayservice
          image: tibinlukose/gateway-app
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gatewayservice
  namespace: demo-app
spec:
  type: ClusterIP
  selector:
    app: gatewayservice
  ports:
    - port: 8080
      name: gateway-port
      targetPort: 8090

