server:
  port: 8081
partners:
  version:
  news:
    - id: 1
      name: bbc
      url: http://feeds.bbci.co.uk/news/world/rss.xml
      type: WORLD
      enabled: true
    - id: 2
      name: techrepublic
      url: https://www.techrepublic.com/rssfeeds/articles/
      type: TECHNOLOGY
      enabled: true
    - id: 3
      name: fox
      url: https://api.foxsports.com/v1/rss?partnerKey=zBaFxRyGKCfxBagJG9b8pqLyndmvo7UU
      type: SPORTS
      enabled: true
spring:
  jackson:
    deserialization:
      ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT : true
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true